// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8YbDPuX4u4O6dlNA-jpocr2VG0SbvxBk',
    appId: '1:484443841980:android:f257af22b01489e159b7b9',
    messagingSenderId: '484443841980',
    projectId: 'tutormatch-a7439',
    databaseURL: 'https://tutormatch-a7439-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tutormatch-a7439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZXXIvSCYLKy48A59rk-synC0KjuK8ips',
    appId: '1:484443841980:ios:c54ad2f831d35ca459b7b9',
    messagingSenderId: '484443841980',
    projectId: 'tutormatch-a7439',
    databaseURL: 'https://tutormatch-a7439-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tutormatch-a7439.appspot.com',
    iosBundleId: 'com.example.tutormatch',
  );
}
